name: magic-packet
channels:
  - conda-forge
  - default
dependencies:
  - jupyter=1.0.0
  - kaldi=5.5.992
  - librosa=0.8.1
  - llvmlite=0.37.0
  - numba=0.54.1
  - pandas=1.3.5
  - pip=21.2.4
  - python=3.9.7
  - tqdm=4.62.3
  - pip:
    - montreal-forced-aligner==2.0.0b10
