name: magic-packet
channels:
  - pytorch
  - conda-forge
  - default
dependencies:
  - jupyter=1.0.0
  - kaldi=5.5.992
  - librosa=0.8.1
  - llvmlite=0.37.0
  - numba=0.54.1
  - numpy=1.20.3
  - pandas=1.3.5
  - pip=21.2.4
  - portaudio=19.6.0
  - python=3.9.7
  - pytorch=1.10.1
  - swig=4.0.2
  - tensorboard=2.7.0
  - tqdm=4.62.3
  - pip:
    - montreal-forced-aligner==2.0.0b10
    - https://github.com/castorini/howl/archive/master.zip
