name: magic-packet
channels:
  - conda-forge
  - default
dependencies:
  - kaldi=5.5.992
  - libsndfile=1.0.31
  - llvmlite=0.37.0
  - numba=0.54.1
  - pip=21.3.1
  - python=3.9
  - sox=14.4.2
  - pip:
    - montreal-forced-aligner==2.0.0b9
