name: dataset
channels:
  - pytorch
  - conda-forge
  - default
dependencies:
  - coloredlogs=15.0.1
  - jupyter=1.0.0
  - librosa=0.8.1
  - montreal-forced-aligner=2.0.0b9
  - numpy=1.20.3
  - pandas=1.3.5
  - pip=21.2.4
  - pyaudio=0.2.11
  - pydantic=1.8.2
  - pysoundfile=0.10.3.post1
  - python=3.9.7
  - pytorch=1.10.1
  - tensorboard=2.7.0
  - torchaudio=0.10.1
  - torchvision=0.11.2
  - tqdm=4.61.2
  - pip:
    - https://github.com/castorini/howl/archive/master.zip
