name: magic-packet
channels:
  - apple
  - conda-forge
  - default
dependencies:
  - ansiwrap=0.8.4
  - black=21.7b0
  - click=8.0.3
  - flake8=4.0.1
  - isort=5.10.1
  - jupyter=1.0.0
  - kaldi=5.5.992
  - libsndfile=1.0.31
  - llvmlite=0.37.0
  - matplotlib=3.5.1
  - numba=0.54.1
  - numpy=1.19.5
  - pip=21.3.1
  - pre-commit=2.16.0
  - python=3.9
  - seaborn=0.11.2
  - tensorflow-deps=2.7.0
  - tqdm=4.62.3
  - pip:
      - montreal-forced-aligner==2.0.0rc3
      - pydub==0.25.1
      - tensorflow-datasets==4.4.0
      - tensorflow-macos==2.7.0
      - tensorflow-metal==0.3.0
      - tensorflow-model-optimization==0.7.0
